### ISSUE TITLE
Registry login information

### ISSUE THREAD

**Issue by paavan98pm** [notaryproject/distribution#8]
Is there a `docker login` credential information when running `docker run -it -p 5000:5000 --name oci-artifact-registry notaryv2/registry:nv2-prototype-2`? I can raise a PR to add this to the docs. Thanks. /cc @SteveLasker

**Comment by SteveLasker** [comment]
The CNCF distribution instance is unauthenticated as it's agnostic of everything.
So, once instanced, you can push/pull to your hearts content.
Is there a need to create a cred manager for this that I'm not thinking of?

**Comment by paavan98pm** [comment]
@SteveLasker sorry, I was pointing to the wrong port (5001) from the output of `docker run` than following the instructions. 5000 worked fine without authentication. Interestingly, two signature jwts were pushed for the image since I signed them twice using the same certs.

```bash
❯ docker nv2 push localhost:5000/test:1.2                                              
The push refers to repository [localhost:5000/test]
b2d5eeeaba3a: Preparing
b2d5eeeaba3a: Layer already exists
1.2: digest: sha256:9cb486fa4cef13b030904ce2cf3a5f8512ed206b0bbe63b4cc74af57e1c5e90a size: 527
Pushing signature
signature manifest digest: sha256:5cb4106ad80dd2a95bdea34f0313d4b0cbfcf59efafe031c294aa703e4d3a731 size: 470
signature manifest digest: sha256:dc57c66afca844b6afd270efc4aec8429c07f00b7bce249cbafad3a3bb30f5fe size: 470
```
